"""Initial migration

Revision ID: a7f3d54b2be8
Revises: 7905d227913a
Create Date: 2025-04-05 16:40:49.781412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f3d54b2be8'
down_revision = '7905d227913a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ower_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key(None, 'user', ['ower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ower_id')

    # ### end Alembic commands ###
